let stock0 = {
  data: {
    items: [
      {
        type: 20,
        code: "BABA",
        name: "阿里巴巴",
        value: 119918,
        increment: 551,
        percent: -11.1276,
        current: 143.6,
        chg: -17.98,
      },
      {
        type: 20,
        code: "SH600556",
        name: "天下秀",
        value: 105771,
        increment: 1090,
        percent: 9.99,
        current: 15.31,
        chg: 1.39,
      },
      {
        type: 20,
        code: "SZ300474",
        name: "景嘉微",
        value: 93569,
        increment: -439,
        percent: 0.91,
        current: 195.84,
        chg: 1.76,
      },
      {
        type: 20,
        code: "SZ002466",
        name: "天齐锂业",
        value: 87478,
        increment: -637,
        percent: -2.1,
        current: 106.48,
        chg: -2.28,
      },
      {
        type: 20,
        code: "BILI",
        name: "哔哩哔哩",
        value: 71114,
        increment: 346,
        percent: -17.1665,
        current: 67.12,
        chg: -13.91,
      },
      {
        type: 20,
        code: "SZ002176",
        name: "江特电机",
        value: 64119,
        increment: -29,
        percent: -2.63,
        current: 21.86,
        chg: -0.59,
      },
      {
        type: 20,
        code: "SZ000651",
        name: "格力电器",
        value: 62489,
        increment: 255,
        percent: -0.08,
        current: 35.72,
        chg: -0.03,
      },
      {
        type: 20,
        code: "SH601919",
        name: "中远海控",
        value: 61488,
        increment: -155,
        percent: -1.46,
        current: 14.85,
        chg: -0.22,
      },
    ],
  },
  error_code: 0,
  error_description: "",
};

let stock1 = {
  data: {
    items: [
      {
        type: 22,
        code: "SH600556",
        name: "天下秀",
        value: 107426,
        increment: 1655,
        percent: 9.99,
        current: 15.31,
        chg: 1.39,
      },
      {
        type: 22,
        code: "SZ300474",
        name: "景嘉微",
        value: 93139,
        increment: -430,
        percent: 0.76,
        current: 195.56,
        chg: 1.48,
      },
      {
        type: 22,
        code: "SZ002466",
        name: "天齐锂业",
        value: 86604,
        increment: -874,
        percent: -2.23,
        current: 106.33,
        chg: -2.43,
      },
      {
        type: 22,
        code: "SZ002176",
        name: "江特电机",
        value: 64098,
        increment: -21,
        percent: -2.54,
        current: 21.88,
        chg: -0.57,
      },
      {
        type: 22,
        code: "SZ000651",
        name: "格力电器",
        value: 62335,
        increment: -154,
        percent: -0.31,
        current: 35.64,
        chg: -0.11,
      },
      {
        type: 22,
        code: "SH601919",
        name: "中远海控",
        value: 61648,
        increment: 160,
        percent: -1.39,
        current: 14.86,
        chg: -0.21,
      },
      {
        type: 22,
        code: "SH600763",
        name: "通策医疗",
        value: 57745,
        increment: -504,
        percent: -1.79,
        current: 212.3,
        chg: -3.86,
      },
      {
        type: 22,
        code: "SZ002487",
        name: "大金重工",
        value: 52409,
        increment: -2904,
        percent: -2.62,
        current: 48.25,
        chg: -1.3,
      },
    ],
  },
  error_code: 0,
  error_description: "",
};

let stock2 = {
  data: {
    items: [
      {
        type: 23,
        code: "09988",
        name: "阿里巴巴-SW",
        value: 52333,
        increment: 709,
        percent: -10.26,
        current: 140,
        chg: -16,
      },
      {
        type: 23,
        code: "00700",
        name: "腾讯控股",
        value: 39761,
        increment: -162,
        percent: -1.29,
        current: 490.4,
        chg: -6.4,
      },
      {
        type: 23,
        code: "01810",
        name: "小米集团-W",
        value: 14093,
        increment: -33,
        percent: -0.95,
        current: 20.95,
        chg: -0.2,
      },
      {
        type: 23,
        code: "02599",
        name: "祥生控股集团",
        value: 11991,
        increment: 10,
        percent: 16.98,
        current: 1.86,
        chg: 0.27,
      },
      {
        type: 23,
        code: "09626",
        name: "哔哩哔哩-SW",
        value: 10649,
        increment: 107,
        percent: 0,
        current: 630,
        chg: 0,
      },
      {
        type: 23,
        code: "03333",
        name: "中国恒大",
        value: 10141,
        increment: -60,
        percent: 1.52,
        current: 2.68,
        chg: 0.04,
      },
      {
        type: 23,
        code: "03690",
        name: "美团-W",
        value: 8171,
        increment: 18,
        percent: -3.08,
        current: 276.6,
        chg: -8.8,
      },
      {
        type: 23,
        code: "03800",
        name: "保利协鑫能源",
        value: 8147,
        increment: 40,
        percent: 1.48,
        current: 3.43,
        chg: 0.05,
      },
    ],
  },
  error_code: 0,
  error_description: "",
};

let stock3 = {
  data: {
    items: [
      {
        type: 21,
        code: "BABA",
        name: "阿里巴巴",
        value: 120048,
        increment: 130,
        percent: -11.1276,
        current: 143.6,
        chg: -17.98,
      },
      {
        type: 21,
        code: "BILI",
        name: "哔哩哔哩",
        value: 71107,
        increment: -7,
        percent: -17.1665,
        current: 67.12,
        chg: -13.91,
      },
      {
        type: 21,
        code: "JD",
        name: "京东",
        value: 58435,
        increment: 180,
        percent: 5.9531,
        current: 88.1,
        chg: 4.95,
      },
      {
        type: 21,
        code: "NVDA",
        name: "英伟达",
        value: 46596,
        increment: 72,
        percent: 8.2499,
        current: 316.75,
        chg: 24.14,
      },
      {
        type: 21,
        code: "TSLA",
        name: "特斯拉",
        value: 34980,
        increment: 1,
        percent: 0.6768,
        current: 1096.38,
        chg: 7.37,
      },
      {
        type: 21,
        code: "AAPL",
        name: "苹果",
        value: 26885,
        increment: 111,
        percent: 2.8536,
        current: 157.87,
        chg: 4.38,
      },
      {
        type: 21,
        code: "VIPS",
        name: "唯品会",
        value: 25189,
        increment: 182,
        percent: -17.9886,
        current: 10.03,
        chg: -2.2,
      },
      {
        type: 21,
        code: "PDD",
        name: "拼多多",
        value: 16796,
        increment: 10,
        percent: -5.2245,
        current: 85.08,
        chg: -4.69,
      },
    ],
  },
  error_code: 0,
  error_description: "",
};

let fundList = {
  data: {
    title: "发现好机会",
    more_url: "https://danjuanfunds.com/activity/HotFund",
    tab: [
      {
        tab_name: "低估指数",
        comment: "关注低估指数，把握买卖时机",
        tips: "低估指数：PE高低以十年期国债收益率倒数为判断标准，不足5%按照5%计算；因此以PE 20为判断标准，PE/PB 绝对值低于20且百分位低于30%，定义该指数进入低估区域。",
        tab_type: "3",
        items: [
          {
            img_src: "https://xqimg.imedao.com/1799d61b1cd107643fe88a52.png",
            name: "中证红利",
            code: "SH000922",
            content: [
              {
                value: "5.98",
                desc: "PE",
                color: false,
              },
              {
                value: "0.08%",
                desc: "PE百分位",
                color: false,
              },
              {
                value: "12.28%",
                desc: "ROE",
                color: false,
              },
            ],
            url: "https://danjuanfunds.com/dj-valuation-table-detail/SH000922",
          },
          {
            img_src: "https://xqimg.imedao.com/1799d61b1cd107643fe88a52.png",
            name: "上证红利",
            code: "SH000015",
            content: [
              {
                value: "5.15",
                desc: "PE",
                color: false,
              },
              {
                value: "0.08%",
                desc: "PE百分位",
                color: false,
              },
              {
                value: "11.86%",
                desc: "ROE",
                color: false,
              },
            ],
            url: "https://danjuanfunds.com/dj-valuation-table-detail/SH000015",
          },
          {
            img_src: "https://xqimg.imedao.com/1799d61b1cd107643fe88a52.png",
            name: "标普红利",
            code: "CSPSADRP",
            content: [
              {
                value: "5.12",
                desc: "PE",
                color: false,
              },
              {
                value: "0.20%",
                desc: "PE百分位",
                color: false,
              },
              {
                value: "12.45%",
                desc: "ROE",
                color: false,
              },
            ],
            url: "https://danjuanfunds.com/dj-valuation-table-detail/CSPSADRP",
          },
        ],
      },
      {
        tab_name: "定投榜单",
        comment: "近1月定投人气排名",
        tips: "定投榜单：按照近期定投的人次以及金额情况综合评估定投人气值筛选榜单基金，其中定投收益率，按照周定投规则回测模拟近三年连续定投得到的收益率，普通定投按照固定金额回测，智能定投按照上涨多投下跌少投规则回测。",
        tab_type: "4",
        items: [
          {
            img_src: "https://xqimg.imedao.com/1799d627d901076c3fe5fb69.png",
            name: "富国天惠成长LOF",
            code: "161005",
            content: [
              {
                value: "41.69",
                desc: "近3年普通定投收益率",
                color: true,
              },
              {
                value: "54.01",
                desc: "近3年智能定投收益率",
                color: true,
              },
            ],
            num_desc: "定投人气值1073",
            url: "https://danjuanfunds.com/funding/161005",
          },
          {
            img_src: "https://xqimg.imedao.com/1799d62cd54109b03fdfddda.png",
            name: "易方达蓝筹精选混合",
            code: "005827",
            content: [
              {
                value: "51.66",
                desc: "近3年普通定投收益率",
                color: true,
              },
              {
                value: "83.12",
                desc: "近3年智能定投收益率",
                color: true,
              },
            ],
            num_desc: "定投人气值918",
            url: "https://danjuanfunds.com/funding/005827",
          },
          {
            img_src: "https://xqimg.imedao.com/1799d631858109b83fc10085.png",
            name: "中欧医疗健康混合A",
            code: "003095",
            content: [
              {
                value: "70.77",
                desc: "近3年普通定投收益率",
                color: true,
              },
              {
                value: "103.54",
                desc: "近3年智能定投收益率",
                color: true,
              },
            ],
            num_desc: "定投人气值770",
            url: "https://danjuanfunds.com/funding/003095",
          },
        ],
      },
    ],
  },
  result_code: 0,
};

// export default { fundList, stock: { stock0, stock1, stock2, stock3 } };
export const data = { fundList, stock: { stock0, stock1, stock2, stock3 } };
